name: Linkinator

on:
  schedule:
    - cron: '0 0 * * 1'

env:
  GATSBY_DEFAULT_SITE_URL: https://neon.com
permissions:
  contents: read

jobs:
  linkinator:
    name: 'Checks broken links'
    runs-on:
      group: neondatabase-protected-runner-group
      labels: linux-ubuntu-latest
    continue-on-error: true
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v7
      - uses: JustinBeckwith/linkinator-action@12f7a61a56e5e75d659f0dfd6357e2d852ede281 # v2.5.0
        with:
          paths: ${{ env.GATSBY_DEFAULT_SITE_URL }}
          concurrency: 100
          recurse: true
          retry: true
          skip: ".*(\\.js|\\.css|\\.woff2)$"
          linksToSkip: >-
            linkedin.com,
            googleapis.com
          verbosity: 'ERROR'
          markdown: false
